// Per-person app icon generator.
//
// Returns two flavors:
//   - appIconSvgDataUri(person)  — synchronous SVG data URI. Use for
//     <link rel="icon"> where SVG is broadly supported (modern
//     browsers, incl. iOS Safari tab favicon).
//   - appIconPngDataUri(person)  — async PNG data URI generated by
//     rasterizing the same SVG through a Canvas element. Use for
//     <link rel="apple-touch-icon"> since iOS Home-Screen capture
//     historically requires PNG and silently falls back when fed SVG.
//
// We use a deliberately simple SVG — solid rect + text, no gradients
// or filters — so the in-browser Image→Canvas pipeline rasterizes it
// reliably across Safari, Chrome, and Firefox.

const CONFIG = {
  jonathan: {
    bg: '#16102a',
    initial: 'J',
    color: '#fdd835',
    font: 'Georgia, serif',
    weight: '400',
    italic: false,
  },
  helen: {
    bg: '#f5f1ec',
    initial: 'H',
    color: '#6b8f8f',
    font: "'Playfair Display', Georgia, serif",
    weight: '400',
    italic: true,
  },
  aurelia: {
    bg: '#fdf0f4',
    initial: 'A',
    color: '#c2185b',
    font: 'system-ui, -apple-system, sans-serif',
    weight: '700',
    italic: false,
  },
  rafa: {
    bg: '#0a0e1a',
    initial: 'R',
    color: '#d32f2f',
    font: 'system-ui, -apple-system, sans-serif',
    weight: '900',
    italic: false,
  },
}

export const PERSON_APP_TITLE = {
  jonathan: 'Road Trip',
  helen: 'Road Trip',
  aurelia: 'Road Trip',
  rafa: 'ROAD TRIP',
}

/** Returns a raw SVG string (not URI-encoded). */
function buildSvg(personKey) {
  const c = CONFIG[personKey] || CONFIG.jonathan
  const italic = c.italic ? 'italic' : 'normal'
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">` +
    `<rect width="512" height="512" rx="96" ry="96" fill="${c.bg}"/>` +
    `<text x="256" y="368" text-anchor="middle" ` +
    `font-family=${JSON.stringify(c.font)} ` +
    `font-size="320" font-weight="${c.weight}" font-style="${italic}" ` +
    `fill="${c.color}">${c.initial}</text>` +
    `</svg>`
  )
}

/** Sync SVG data URI — safe to use immediately on render. */
export function appIconSvgDataUri(personKey) {
  return 'data:image/svg+xml,' + encodeURIComponent(buildSvg(personKey))
}

const PNG_CACHE = {}

/**
 * Rasterizes the per-person SVG to a PNG data URI via an HTML
 * Canvas. Cached per person so subsequent calls return instantly.
 */
export function appIconPngDataUri(personKey) {
  if (typeof window === 'undefined') return Promise.resolve(null)
  if (PNG_CACHE[personKey]) return Promise.resolve(PNG_CACHE[personKey])

  return new Promise((resolve, reject) => {
    const svg = buildSvg(personKey)
    const blob = new Blob([svg], { type: 'image/svg+xml' })
    const objectUrl = URL.createObjectURL(blob)
    const img = new Image()
    img.decoding = 'async'

    const cleanup = () => URL.revokeObjectURL(objectUrl)

    img.onload = () => {
      try {
        const size = 512
        const canvas = document.createElement('canvas')
        canvas.width = size
        canvas.height = size
        const ctx = canvas.getContext('2d')
        ctx.drawImage(img, 0, 0, size, size)
        const pngUri = canvas.toDataURL('image/png')
        PNG_CACHE[personKey] = pngUri
        cleanup()
        resolve(pngUri)
      } catch (err) {
        cleanup()
        reject(err)
      }
    }
    img.onerror = (err) => {
      cleanup()
      reject(err)
    }
    img.src = objectUrl
  })
}
