// Photo fixtures for Playwright tests.
//
// `setInputFiles` accepts a file path on disk OR a
// `{ name, mimeType, buffer }` shape; the buffer shape keeps fixtures
// inline and deterministic. PNGs are decoded by the real Canvas API
// in headless Chromium during preparePhotoForUpload(), so the
// downscale code path is genuinely exercised.

import { Buffer } from 'node:buffer'
import zlib from 'node:zlib'

// 256x192 solid red PNG, generated by the writer below so we never
// commit a binary fixture and a tweak to the writer can't desync
// from a stale base64 string.
export function redPhotoFile(name = 'beach.png') {
  return {
    name,
    mimeType: 'image/png',
    buffer: makeUniformPng(256, 192, [201, 59, 26]),
  }
}

// A larger PNG so the downscale path crosses the 2048 max-edge cap.
export function bigPhotoFile({ width = 3000, height = 2250 } = {}) {
  return {
    name: `big-${width}x${height}.png`,
    mimeType: 'image/png',
    buffer: makeUniformPng(width, height, [180, 70, 40]),
  }
}

// "Wrong file type" fixture: MP4 ftyp box. Enough for type sniffing,
// not enough to play. Exercises the 'is-video' rejection branch.
const MP4_FTYP_B64 = 'AAAAGGZ0eXBpc29tAAACAGlzb21pc28y'
export function mp4FileForRejection(name = 'clip.mp4') {
  return {
    name,
    mimeType: 'video/mp4',
    buffer: Buffer.from(MP4_FTYP_B64, 'base64'),
  }
}

// TIFF "magic" header: triggers the 'unsupported-image' branch.
export function tiffFileForRejection() {
  return {
    name: 'shot.tiff',
    buffer: Buffer.from('II* ', 'binary'),
    mimeType: 'image/tiff',
  }
}

// --- minimal PNG writer ----------------------------------------------
//
// Produces a valid uniform-color PNG of arbitrary dimensions without
// pulling in sharp or pngjs. Used for both the small and the "big"
// fixtures.

function makeUniformPng(width, height, [r, g, b]) {
  const ihdr = Buffer.alloc(13)
  ihdr.writeUInt32BE(width, 0)
  ihdr.writeUInt32BE(height, 4)
  ihdr[8] = 8 // bit depth
  ihdr[9] = 2 // RGB
  ihdr[10] = 0
  ihdr[11] = 0
  ihdr[12] = 0

  const rowLen = 1 + width * 3
  const raw = Buffer.alloc(rowLen * height)
  for (let y = 0; y < height; y++) {
    raw[y * rowLen] = 0 // filter byte
    for (let x = 0; x < width; x++) {
      const off = y * rowLen + 1 + x * 3
      raw[off] = r
      raw[off + 1] = g
      raw[off + 2] = b
    }
  }
  const compressed = zlib.deflateSync(raw)

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', compressed),
    chunk('IEND', Buffer.alloc(0)),
  ])
}

function chunk(type, data) {
  const len = Buffer.alloc(4)
  len.writeUInt32BE(data.length, 0)
  const typeBuf = Buffer.from(type, 'ascii')
  const crcInput = Buffer.concat([typeBuf, data])
  const crc = Buffer.alloc(4)
  crc.writeUInt32BE(crc32(crcInput), 0)
  return Buffer.concat([len, typeBuf, data, crc])
}

let crcTable = null
function crc32(buf) {
  if (!crcTable) {
    crcTable = new Uint32Array(256)
    for (let n = 0; n < 256; n++) {
      let c = n
      for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
      crcTable[n] = c
    }
  }
  let c = 0xffffffff
  for (let i = 0; i < buf.length; i++) c = crcTable[(c ^ buf[i]) & 0xff] ^ (c >>> 8)
  return (c ^ 0xffffffff) >>> 0
}
